import './globals.css'
import { Quicksand } from 'next/font/google'

const quicksand = Quicksand({ subsets: ['latin'], variable: '--font-quicksand' })

export const metadata = {
  title: 'Site SMA',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${quicksand.variable} text-slate-950 bg-gradient-to-r from-malachite-50 to-malachite-200 `}>{children}</body>
    </html>
  )
}
